### ISSUE TITLE
Possibly broken in Monterey

### ISSUE THREAD

**Issue by OKNoah** [halo/LinkLiar#44] opened 2021-06-12 03:48 UTC
When I try the command `ifconfig en0 ether f9:e8:15:e3:39:dd` (as sudo or not), I get the message

```
ifconfig: ioctl (SIOCAIFADDR): Operation not supported on socket
```

So I downloaded this app hoping it might work, just no joy. No error or anything, the MAC just stays the same no matter the settings.

**Comment by halo** [comment] 2021-06-13 10:08
Hi! Thank you for your report. I'm always glad to see beta testers 😄

Under the hood, LinkLiar does exactly that - run the `ifconfig` command. And if the command works, LinkLiar will work. If it doesn't work manually, LinkLiar won't be able to do much either.

So, first you'd need to figure out whether it is generally supported on Monetery. You might remember that spoofing stopped working altogether [some time ago](https://github.com/halo/LinkLiar/issues/33) and it was a mistake by Apple. It could be the same now.

What I **do** know is that not all MAC addresses work. So please try a dozen different addresses and if all fail, we're probably out of luck until this issue get's wider attention and eventually reaches Apple (still hoping they did not deactivate this on purpose, but I do not think they would do that)

Final question: did it work on that very machine before installing Monterey?

**Comment by halo** [comment] 2021-08-31 20:51
Hi! 👋🏻 Any news on this?

**Comment by halo** [comment] 2021-10-21 09:35
Hi @Dbrunello 

Thank you for your report. Please be more specific on what you mean by "don't work". 

Also, please read my previous post (higher up on this page) carefully and try the things I suggested there and let me know the results.

Thank you!

**Comment by andrew7321999** [comment] 2022-02-28 18:53
OK, the problem is slolved for me. Currently using 12.1(21C52) Monterey, M1pro MacBook pro. you set the MAC address on Linklier, and try reboot. It works for my MacBook and MacBook pro 2017 with intel i7 processor. 

Probably there is a moment that "ifconfig en0 ether xx:xx:xx:xx:xx:xx " works on terminal while its booting. 
make sure you add linklier on Login Items(Preference-User and Groups-Login Items) 
Hope this helps you.

P.s. I survive in school with using teachers wifi with arp -a command. Haha.

**Comment by halo** [comment] 2022-03-03 19:47
> Probably there is a moment that "ifconfig en0 ether xx:xx:xx:xx:xx:xx " works on terminal while its booting.
> make sure you add linklier on Login Items(Preference-User and Groups-Login Items)

That's interesting. Well, it should be enough if you have this option turned on:

<img width="390" alt="screenshot" src="https://user-images.githubusercontent.com/11441/156640967-b6341c8f-5aa4-4971-89c8-d3a154a5ebb2.png">

The LinkLiar "app" ist just a menu bar GUI that does nothing in itself. It is the background daemon that really does all the work. If you check that checkbox, the daemon is activated on boot (even before you log in!).

Adding the LinkLiar "app" to your login items only becomes active **after** you logged in. By that time, the daemon was already active.

I'll close this for now. If there are any more Monterey-related questions, feel free to re-open this issue.

**Closed by halo** 2022-03-03 19:47 UTC
Labels: investigating

**Comment by cyb3rw0lf** [comment] 2022-04-23 09:49
Would be great to have the monterey fix implemented in the app as described in this post

MAC address spoofing not working in macOS 12 Monterey - https://developer.apple.com/forums/thread/684745?answerId=707230022#707230022

First, disassociate from any network:
`sudo /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -z`

Then change your lladdr:
`sudo ifconfig <intf> lladdr 00:bb:cc:dd:ee:ff `

Then rejoin the WLAN normally.

**Comment by halo** [comment] 2022-04-25 17:01
I can confirm that changing the MAC address is not possible on Monterey while connected to a network. So, I [changed](https://github.com/halo/LinkLiar/commit/749e7189009d12ab0151a08e0185033b22e3f377) LinkLiar to disassociate from any network before attempting to change the MAC address.

Originally, it looked to me that LinkLiar was working just fine on Monterey. That is because the LinkLiar daemon changed the MAC address on boot *before* any network was connected to. I didn't notice that *after that* the address could not be updated to something else.

> Then rejoin the WLAN normally.

I'm not sure about this yet and will have to think about it first. I'm afraid there might be edge cases (e.g. on boot) where one doesn't want to automatically re-associate. Also, I'm not sure [it's possible](https://stackoverflow.com/q/62368835) using Swift or [possible](https://stackoverflow.com/a/51014638) using the CLI.

Do you know of a way to (re-)connect to a Wi-Fi without knowing the password in macOS and without using the trackpad? :)

**Comment by halo** [comment] 2022-04-25 17:12
This is the pre-release, I'd appreciate if you try it out and let me know whether it works:

https://github.com/halo/LinkLiar/releases/tag/3.1.0

**Comment by cyb3rw0lf** [comment] 2022-04-25 17:29
From CLI it work this way

1. Fetch SSID name:
`airport -I`
2. Change MAC Address
3. Disconnect from current WLAN
`airport -z`
4. Reconnect to previous WLAN
`/usr/sbin/networksetup -setairportnetwork en0 Internet`

Maybe it also work with swift is not specifying any password (no idea)
```
  func connect(to name: String) {
      interface?.associate(name: SSIDNAME)
  }
```

**Comment by cyb3rw0lf** [comment] 2022-04-25 17:45
> This is the pre-release, I'd appreciate if you try it out and let me know whether it works:
> 
> https://github.com/halo/LinkLiar/releases/tag/3.1.0

For me it doesn't disassociate, so unless I manually do the disassociation it doesn't work. (same as previous build)

**Comment by halo** [comment] 2022-04-25 18:09
Then you installed the new version, did it ask you to "Re-Authorize LinkLiar" (that is, the daemon)?

Let's try to confirm that you have the right version version installed.

* Open LinkLiar and hold the `Option` ⌥ key
* Over over the "Advanced" menu item

Do you have version `3.1.0`?

<img width="211" alt="Screen Shot 2022-04-25 at 20 01 18" src="https://user-images.githubusercontent.com/11441/165147448-1911a175-2494-44c0-afe2-7f2baa03a60f.png">

Can you try "Install Daemon"?

---

> /usr/sbin/networksetup -setairportnetwork en0 SSIDNAME

You are right, this works! It's a bit brittle to connect to a SSID instead of a BSSID, but it should be good enough.

**Comment by halo** [comment] 2022-04-25 19:15
I've updated the version to `3.2.0`. It now re-associates to the network it was connected to. If you could give it another try.

I think I'll have to add an option to disable this feature, I'm not sure yet.

**Comment by cyb3rw0lf** [comment] 2022-04-25 19:38
> I've updated the version to `3.2.0`. It now re-associates to the network it was connected to. If you could give it another try.
> 
> I think I'll have to add an option to disable this feature, I'm not sure yet.

yes it works! thanks

There's a weird behavior if I have two SSID both with auto-join and I'm connected to SSID1, when I click to change mac address on linkliar it connect to SSID2 afterwards. There might be some internal behavior that kicks in before you command? Something like if it disconnect from one SSID after a while it tried another one. Did you put a sleep or timeout between the mac change and the SSID reconnect?

**Comment by cyb3rw0lf** [comment] 2022-04-25 19:52
if I run the command via CLI it also connect twice actually so I think nothing we can do there but the reconnection is much faster compared than when I do it on linkliar

`airport -z && sleep 1 && ifconfig en0 ether 00:bb:cc:dd:ee:dd && sleep 1 && networksetup -setairportnetwork en0 SSID1`
